#!/usr/bin/env bash

cd $(dirname ${BASH_SOURCE[0]})

if [[ -n $(git status -s) ]]; then
    echo "Changes found. doing changes"
    export commit_title=$(date)
    git add -A && git commit -m "$commit_title"
    ssh-agent bash -c 'ssh-add /home/morales/Escritorio/gittest/id_rsa; git push origin master git@github.com:emorales15b/automatic-commit.git'
else
    echo "No changes found."
fi
